version: '3.1'

services:

  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass

  pgserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
